#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /tools/xilinx/11.5/EDK
NON_CYG_XILINX_EDK_DIR = /tools/xilinx/11.5/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = virtex5

DEVICE = xc5vsx95tff1136-1

LANGUAGE = vhdl

SEARCHPATHOPT = 
GLOBAL_SEARCHPATHOPT = 

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT) -msg __xps/ise/xmsgprops.lst

OBSERVE_PAR_OPTIONS = -error yes

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

EPB_OPB_BRIDGE_INST_BOOTLOOP = $(BOOTLOOP_DIR)/epb_opb_bridge_inst.elf

BRAMINIT_ELF_FILES =  
BRAMINIT_ELF_FILE_ARGS =  

ALL_USER_ELF_FILES = 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT) -msg __xps/ise/xmsgprops.lst -s mti


LIBRARIES =  \
       epb_opb_bridge_inst/lib/libxil.a 

LIBSCLEAN_TARGETS = epb_opb_bridge_inst_libsclean 

PROGRAMCLEAN_TARGETS = 

CORE_STATE_DEVELOPMENT_FILES = /scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/arp_cache.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/cpu_buffer.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_ctrl_fifo.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_fifo_bram.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_fifo_dist.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_cpu_fifo.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_cpu_size_fifo.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_packet_ctrl_fifo.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_packet_fifo.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_fifo_ext.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/xaui_phy_v1_00_a/netlist/xaui_v7_2.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/arp_cache.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/cpu_buffer.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_ctrl_fifo.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_fifo_bram.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_fifo_dist.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_cpu_fifo.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_cpu_size_fifo.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_packet_ctrl_fifo.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_packet_fifo.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_fifo_ext.ngc \
/scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/pcores/xaui_phy_v1_00_a/netlist/xaui_v7_2.ngc \
pcores/roach_infrastructure_v1_00_a/hdl/verilog/roach_infrastructure.v \
pcores/reset_block_v1_00_a/hdl/verilog/reset_block.v \
pcores/epb_opb_bridge_v1_00_a/hdl/verilog/epb_opb_bridge.v \
pcores/epb_infrastructure_v1_00_a/hdl/verilog/epb_infrastructure.v \
pcores/sys_block_v1_00_a/hdl/verilog/sys_block.v \
pcores/xaui_infrastructure_v1_00_a/hdl/verilog/xaui_infrastructure.v \
pcores/xaui_infrastructure_v1_00_a/hdl/verilog/transceiver_bank.v \
pcores/xaui_infrastructure_v1_00_a/hdl/verilog/transceiver.v \
pcores/signal_rename_v1_00_a/hdl/verilog/signal_rename.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/arp_cache.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/cpu_buffer.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/kat_ten_gb_eth.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/opb_attach.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/rx_packet_ctrl_fifo.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/rx_packet_fifo_bram.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/rx_packet_fifo_dist.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/tge_rx.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/tge_tx.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/tx_packet_ctrl_fifo.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/tx_packet_fifo.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/tx_fifo_ext.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/ten_gig_eth_mac.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/mac_rx.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/mac_tx.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/mac_hard_crc.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/xaui_phy.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/xaui_v7_2.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/deskew_state.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/fix_term.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/pcs_deskew.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/pcs_rx.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/pcs_sync.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/pcs_tx.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/sync_state.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/tx_state.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/xaui_kat.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/xaui_kat.vh \
pcores/gpio_simulink2ext_v1_00_a/hdl/vhdl/gpio_simulink2ext.vhd \
pcores/opb_register_simulink2ppc_v1_00_a/hdl/verilog/opb_register_simulink2ppc.v \
pcores/bram_if_v1_00_a/hdl/vhdl/bram_if.vhd \
pcores/opb_register_ppc2simulink_v1_00_a/hdl/verilog/opb_register_ppc2simulink.v

WRAPPER_NGC_FILES = implementation/infrastructure_inst_wrapper.ngc \
implementation/reset_block_inst_wrapper.ngc \
implementation/opb0_wrapper.ngc \
implementation/epb_opb_bridge_inst_wrapper.ngc \
implementation/epb_infrastructure_inst_wrapper.ngc \
implementation/sys_block_inst_wrapper.ngc \
implementation/xaui_infrastructure_inst_wrapper.ngc \
implementation/arb_clk_dcm_wrapper.ngc \
implementation/arb_clk_dcm_phasegen_wrapper.ngc \
implementation/rename_fab_clk_wrapper.ngc \
implementation/roachf_2048ch_2gpu_gbe_gpu_wrapper.ngc \
implementation/xaui_phy_3_wrapper.ngc \
implementation/roachf_2048ch_adcs_quadc0_wrapper.ngc \
implementation/roachf_2048ch_adcs_quadc1_wrapper.ngc \
implementation/roachf_2048ch_leds_led1_arm_wrapper.ngc \
implementation/roachf_2048ch_leds_led2_sync_wrapper.ngc \
implementation/roachf_2048ch_leds_led4_eq_clip_wrapper.ngc \
implementation/roachf_2048ch_leds_led5_adc_clip_wrapper.ngc \
implementation/roachf_2048ch_loopback_loop_cnt0_wrapper.ngc \
implementation/roachf_2048ch_loopback_loop_err_cnt0_wrapper.ngc \
implementation/roachf_2048ch_loopback_loopback_mux0_mcnt_wrapper.ngc \
implementation/roachf_2048ch_loopback_statii_wrapper.ngc \
implementation/roachf_2048ch_switch_gbe_sw_wrapper.ngc \
implementation/xaui_phy_0_wrapper.ngc \
implementation/roachf_2048ch_transpose_dbuf_ct_bram_shared_bram_ramif_wrapper.ngc \
implementation/roachf_2048ch_transpose_dbuf_ct_bram_shared_bram_ramblk_wrapper.ngc \
implementation/roachf_2048ch_transpose_dbuf_ct_bram_shared_bram_wrapper.ngc \
implementation/roachf_2048ch_transpose_dbuf_ct_bram_shared_bram1_ramif_wrapper.ngc \
implementation/roachf_2048ch_transpose_dbuf_ct_bram_shared_bram1_ramblk_wrapper.ngc \
implementation/roachf_2048ch_transpose_dbuf_ct_bram_shared_bram1_wrapper.ngc \
implementation/roachf_2048ch_control_ctl_regs_ant_base_wrapper.ngc \
implementation/roachf_2048ch_control_ctl_regs_feng_ctl_wrapper.ngc \
implementation/roachf_2048ch_control_ctl_regs_gbe_sw_port_wrapper.ngc \
implementation/roachf_2048ch_control_ctl_regs_gpu_ip_wrapper.ngc \
implementation/roachf_2048ch_control_ctl_regs_gpu_port_wrapper.ngc \
implementation/roachf_2048ch_control_ctl_regs_ip_base_wrapper.ngc \
implementation/roachf_2048ch_control_ctl_regs_my_ip_wrapper.ngc \
implementation/roachf_2048ch_control_delay_delay_wrapper.ngc \
implementation/roachf_2048ch_control_eq_coefs_eq0_ctl_wrapper.ngc \
implementation/roachf_2048ch_control_eq_coefs_eq1_ctl_wrapper.ngc \
implementation/roachf_2048ch_control_eq_coefs_eq2_ctl_wrapper.ngc \
implementation/roachf_2048ch_control_eq_coefs_eq3_ctl_wrapper.ngc \
implementation/roachf_2048ch_control_insel_insel_wrapper.ngc \
implementation/roachf_2048ch_control_seed_seed_data_wrapper.ngc \
implementation/roachf_2048ch_status_gbe_gpu_wrapper.ngc \
implementation/roachf_2048ch_status_gbe_sw_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

SDK_EXPORT_DIR = /scratch/zaki/workspace/roachfengine/roachf_2048ch/XPS_ROACH_base/SDK/SDK_Export/hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_BMM = $(SDK_EXPORT_DIR)/$(SYSTEM)_bd.bmm
SYSTEM_HW_HANDOFF_DEP = $(SYSTEM_HW_HANDOFF) $(SYSTEM_HW_HANDOFF_BIT) $(SYSTEM_HW_HANDOFF_BMM)
